# Generated by Django 2.2.7 on 2020-05-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('typeof', models.CharField(choices=[('string', 'Строка'), ('integer', 'Число'), ('bool', 'Да/Нет (булево)'), ('decimal', 'Деньги')], default='string', max_length=8, verbose_name='Тип параметра')),
                ('decor', models.CharField(blank=True, choices=[('color', 'Цвет')], max_length=8, null=True, verbose_name='Оформление, тип отоброжения(в разработке)')),
            ],
            options={
                'verbose_name': 'Параметр (dev)',
                'verbose_name_plural': 'Параметры (dev)',
                'ordering': ('typeof',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParamValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение(строка)')),
                ('int_value', models.IntegerField(blank=True, null=True, verbose_name='Значение(целое число)')),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Значение(денежный формат)')),
                ('bool_value', models.NullBooleanField(max_length=255, verbose_name='Значение(булево)')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='param.Param', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Параметр :значение',
                'verbose_name_plural': 'Параметр :значения',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParamSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof', models.PositiveSmallIntegerField(choices=[(0, 'Новое объявление: автомобиль'), (1, 'Фильтр для главной страницы: объявления')], unique=True, verbose_name='Тип')),
                ('params', models.ManyToManyField(blank=True, to='param.Param', verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'Параметр :набор (dev)',
                'verbose_name_plural': 'Параметр :наборы (dev)',
                'ordering': ('typeof',),
                'abstract': False,
            },
        ),
    ]
